# Generated by Django 3.1.3 on 2020-11-20 21:28

import django.core.validators
from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.random_filename),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.random_filename, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])]),
        ),
    ]
