# Generated by Django 3.1.3 on 2020-11-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
